language: shell
os: linux

jobs:
  include:
    - stage: Run luacheck
      if: tag IS NOT present
      addons:
        apt:
         packages:
           - luarocks
      install: luarocks install --local luacheck
      script: /home/travis/.luarocks/bin/luacheck . --no-color -q
    - stage: Create Retail package
      if: tag IS present
      install: skip
      script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -m .pkgmeta
    - stage: Create Classic package
      if: tag IS present
      install: skip
      script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g 1.13.2
 
notifications:
 email:
   on_success: never
   on_failure: always
